# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d37af4ad4489f139787d7679b1d79011f167cd164e9257e2480c2e5fd453b1dcaca377240fcffa71ae4d2320f57aefffff58f7add7c85707d84683726edc2ae1

test:
  secret_key_base: 1a475f825e464616601302a206a6da5a949a49a4309c56250e7aec2c642af57e28a8cc8c78decb8556e336d98b45905cb6cd5ca658e03acb93c27b59a5789a9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
